export const SET_GIFT_CARDS_LOADING = "SET_GIFT_CARDS_LOADING";
export const SET_GIFT_CARDS = "SET_GIFT_CARDS";

export const SET_CARDMOLA_GIFT_CARDS_LOADING =
  "SET_CARDMOLA_GIFT_CARDS_LOADING";
export const SET_CARDMOLA_GIFT_CARDS = "SET_CARDMOLA_GIFT_CARDS";
export const SET_PAYMENT_DATA =
  "SET_PAYMENT_DATA";
  export const SET_SELECTED_CARDMOLA_COUNTRY =
    "SET_SELECTED_CARDMOLA_COUNTRY";
export const SET_SELECTED_CARDMOLA_GIFT_CARD =
  "SET_SELECTED_CARDMOLA_GIFT_CARD";
export const SET_SELECTED_CARDMOLA_GIFT_CARD_LOADING =
  "SET_SELECTED_CARDMOLA_GIFT_CARD_LOADING";

export const SET_PURCHASED_GIFT_CARDS_LOADING =
  "SET_PURCHASED_GIFT_CARDS_LOADING";
export const SET_PURCHASED_GIFT_CARDS = "SET_PURCHASED_GIFT_CARDS";
