export const ADD_RODUCT_IN_CART = "ADD_RODUCT_IN_CART";
export const REMOVE_PRODUCT_FROM_CART = "REMOVE_PRODUCT_FROM_CART";
export const CLEAR_PRODUCT_CART = "CLEAR_PRODUCT_CART";
export const CALCULATE_ORDER_PRICE = "CALCULATE_ORDER_PRICE";
export const SET_VOUCHER_DISCOUNT = "SET_VOUCHER_DISCOUNT";
export const SET_DELIVERY_ACTIVE_TAB = "SET_DELIVERY_ACTIVE_TAB";
