export const SET_TRANSACTIONS = "SET_TRANSACTIONS";
export const SET_FAMILY_MEMBERS = "SET_FAMILY_MEMBERS";
export const SET_FAMILY_MEMBERS_LOADING = "SET_FAMILY_MEMBERS_LOADING";

export const SET_TRANSACTIONS_HISTORY = "SET_TRANSACTIONS_HISTORY";
export const SET_TRANSACTIONS_HISTORY_LOADING =
  "SET_TRANSACTIONS_HISTORY_LOADING";
export const SET_TRANSACTIONS_HISTORY_ERROR = "SET_TRANSACTIONS_HISTORY_ERROR";
export const SET_TRANSACTIONS_HISTORY_FILTERS =
  "SET_TRANSACTIONS_HISTORY_FILTERS";
