export const SET_NOTIFICATIONS = "SET_NOTIFICATIONS";
export const SET_MESSAGE_NOTIFICATIONS = "SET_MESSAGE_NOTIFICATIONS";
export const SET_MESSAGE_NOTIFICATIONS_LOADING =
  "SET_MESSAGE_NOTIFICATIONS_LOADING";
export const SET_IS_NOTIFICATION_MODAL = "SET_IS_NOTIFICATION_MODAL";
export const SET_CLICKED_NOTIFICATION_DATA = "SET_CLICKED_NOTIFICATION_DATA";
