export const SET_RESTAURANTS = "SET_RESTAURANTS";
export const SET_RESTAURANTS_LOADING = "SET_RESTAURANTS_LOADING";
export const SET_RESTAURANTS_CATEGORIES = "SET_RESTAURANTS_CATEGORIES";
export const SET_RESTAURANTS_ITEMS = "SET_RESTAURANTS_ITEMS";
//export const  SET_RESTAURNTS_ID = 'SET_RESTAURNTS_ID'
export const CONTENT_DISABLED = "CONTENT_DISABLED";
export const APP_DISABLED = "APP_DISABLED";
export const APP_ENABLED = "APP_ENABLED";
export const SET_DELIVERY_LOCATION = "SET_DELIVERY_LOCATION";
export const SET_RESTAURANT_PRODUCTS_CATEGORIES =
  "SET_RESTAURANT_PRODUCTS_CATEGORIES";
export const SET_SELECTED_MERCHANT = "SET_SELECTED_MERCHANT";
