export const SET_VOUCHERS = "SET_VOUCHERS";
export const SET_FAVOURITE_VOUCHERS = "SET_FAVOURITE_VOUCHERS";
export const SET_VOUCHERS_LOADING = "SET_VOUCHERS_LOADING";
export const SET_VOUCHERS_ERROR = "SET_VOUCHERS_ERROR";

export const SET_VOUCHER = "SET_VOUCHER";
export const SET_VOUCHER_LOADING = "SET_VOUCHER_LOADING";
export const SET_VOUCHER_ERROR = "SET_VOUCHER_ERROR";

export const SET_PURCHASED_VOUCHERS = "SET_PURCHASED_VOUCHERS";
export const SET_PURCHASED_VOUCHERS_LOADING = "SET_PURCHASED_VOUCHERS_LOADING";
export const SET_PURCHASED_VOUCHERS_ERROR = "SET_PURCHASED_VOUCHERS_ERROR";
